### ISSUE TITLE
Encrypted metadata does not work

### ISSUE THREAD

**Issue by mkleene** [opentdf/java-sdk#67]
If encrypted metadata is included in the manifest we get a base64 decoding exception during decryption:

```
java.lang.IllegalArgumentException: Illegal base64 character 7b

	at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
	at io.opentdf.platform.sdk.TDF$Reader.doPayloadKeyUnwrap(TDF.java:238)
	at io.opentdf.platform.sdk.TDF.loadTDF(TDF.java:429)
	at io.opentdf.platform.sdk.TDFTest.testSimpleTDFEncryptAndDecrypt(TDFTest.java:71)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

**Comment by mkleene** [comment]
fixed by https://github.com/opentdf/java-sdk/pull/64
